### ISSUE TITLE
Watermark and seal embedded in a .rtf file scrolls along with content

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms#8]
This issue is raised in https://forum.groupdocs.com/t/groupdocs-editor/7835
Hello,

Please find the problematic file attached (sample.rtf). 
[sample.zip](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms/files/3949836/sample.zip).
Before scrolling :
![before](https://user-images.githubusercontent.com/15940608/70613770-0c138a00-1c2b-11ea-9500-1ea601e2f1d6.JPG)
After scrolling :
![after](https://user-images.githubusercontent.com/15940608/70613803-13d32e80-1c2b-11ea-8e12-50a473ff1548.JPG)

When I run application using IIS express and load this attached document, it has a watermark/seal (I replaced the customer's shared watermark and stamp with sample images). Now when I scroll down the document in UI, watermark and seal scrolls along with the content. You can see that in the attached screenshots. 
This application runs successfully on IIS express but when we host it on IIS and try to run hosted app, we get error that is raised [here](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms/issues/7).
Thanks

**Comment by atirtahirgroupdocs** [comment]
@kegor there are some more issue:
If the browser is not maximized, the bottom watermark will disappear, and it will become normal after maximized (even I ran app on two monitors. One with 22' display shows bottom watermark and the other with 15.6' doesn't display bottom watermark).
The footer has a line that disappears even when the browser is maximized.
Please refer to the problematic file that I shared in issue description.
Thanks

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, it's under investigation, we'll let you know when any info will come.

**Comment by kegor** [comment]
@atirtahirgroupdocs, the fix is available in the current (0.5.9) release of https://github.com/groupdocs-total/GroupDocs.Total-Angular. To be sure that you use latest version you could clean `node_modules` folder before next build of the solution.

**Comment by atirtahirgroupdocs** [comment]
@kegor , I deleted node_modules folder (even downloaded project again and did testing from scratch) but I can still reproduce same issue.
Please find the attached screenshots.
[Issue.zip](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms/files/3961222/Issue.zip)

**Comment by kegor** [comment]
@atirtahirgroupdocs, there were made some changes in the repository, could you please try once again?

**Comment by atirtahirgroupdocs** [comment]
@kegor ,
Yes, now watermark and seal are fixed.

**Comment by atirtahirgroupdocs** [comment]
@kegor ,

Watermark and seals are now fixed, they don't scroll along-with page scroll. But there are still some issues:

1. There is no horizontal line at the bottom
2. There is also a problem with the display position of the bottom watermark, which is inconsistent with the print preview display of word

Please find the images attached.
No horizontal line at the bottom
![bottom border](https://user-images.githubusercontent.com/15940608/71155981-caa16100-2260-11ea-9b1a-00452572a524.JPG)
Inconsistent view as compared to Word print preview 
![print preview](https://user-images.githubusercontent.com/15940608/71156053-fe7c8680-2260-11ea-9bc6-58ff41502af8.png)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, i'll take a look at these problems.

**Comment by kegor** [comment]
@atirtahirgroupdocs, we reproduced this problem and working on a solution.

**Comment by atirtahirgroupdocs** [comment]
@bobkovalex is there any update on this issue?

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

Current issue is much more complex then we expected, anyway displaying footer position issue has been fixed and fix should be available after project clean & re-build.

However after saving document you will notice same issues in .rtf document which are going to be fixed in GroupDocs.Editor for .NET 20.02.

The release is planed for next week, but we will start to update our examples ASAP, so that when GroupDocs.Editor for .NET 20.02 comes out publicly the fix will be available right away.

Thanks.

**Comment by atirtahirgroupdocs** [comment]
@bobkovalex ,

There are still some issues.
Please find the screenshots attached. 
[screenshots.zip](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms/files/4244148/screenshots.zip)

Following are the issues:

- Footer horizontal lines still not showing
- Offset shown in lower half
- Print preview will be printed in two pages

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

Footer related issues has been fixed in latest commit.
Checkout master branch in order to get fix.

**Please note**: Print issue has not been fixed yet, it is work in progress.
Anyway, please create a separate ticket for Print issue.

Thanks.
